const matchType = {
  UNKNOWN: {id: 'UNKNOWN'},
  LOCAL_VAR: {id: 'LOCAL_VAR', definitionFiles: ["rs2"], definitionFormat: '$NAME'},
  GLOBAL_VAR: {id: 'GLOBAL_VAR', definitionFiles: ["varp", "varn", "vars"], definitionFormat: '[NAME]', previewDeclaration: true},
  CONSTANT: {id: 'CONSTANT', definitionFiles: ["constant"], definitionFormat: '^NAME', previewDeclaration: true},
  LABEL: {id: 'LABEL', definitionFiles: ["rs2"], definitionFormat: '[label,NAME]', previewDeclaration: true},
  PROC: {id: 'PROC', definitionFiles: ["rs2"], definitionFormat: '[proc,NAME]', previewDeclaration: true},
  TIMER: {id: 'TIMER', types: ["timer"], definitionFiles: ["rs2"], definitionFormat: '[timer,NAME]'},
  SOFTTIMER: {id: 'SOFTTIMER', types: ["softtimer"], definitionFiles: ["rs2"], definitionFormat: '[softtimer,NAME]'},
  QUEUE: {id: 'QUEUE', types: ["queue"], definitionFiles: ["rs2"], definitionFormat: '[queue,NAME]', previewDeclaration: true},
  SEQ: {id: 'SEQ', types: ["seq"], definitionFiles: ["seq"], definitionFormat: '[NAME]'},
  SPOTANIM: {id: 'SPOTANIM', types: ["spotanim"], definitionFiles: ["spotanim"], definitionFormat: '[NAME]'},
  HUNT: {id: 'HUNT', types: ["hunt"], definitionFiles: ["hunt"], definitionFormat: '[NAME]'},
  LOC: {id: 'LOC', types: ["loc"], definitionFiles: ["loc"], definitionFormat: '[NAME]'},
  NPC: {id: 'NPC', types: ["npc"], definitionFiles: ["npc"], definitionFormat: '[NAME]'},
  OBJ: {id: 'OBJ', types: ["namedobj", "obj"], definitionFiles: ["obj"], definitionFormat: '[NAME]'},
  INV: {id: 'INV', types: ["inv"], definitionFiles: ["inv"], definitionFormat: '[NAME]'},
  ENUM: {id: 'ENUM', types: ["enum"], definitionFiles: ["enum"], definitionFormat: '[NAME]', previewDeclaration: true},
  DBROW: {id: 'DBROW', types: ["dbrow"], definitionFiles: ["dbrow"], definitionFormat: '[NAME]', previewDeclaration: true},
  DBTABLE: {id: 'DBTABLE', types: ["dbtable"], definitionFiles: ["dbtable"], definitionFormat: '[NAME]', previewDeclaration: true},
  INTERFACE: {id: 'INTERFACE', types: ["interface"], definitionFiles: ["pack"], definitionFormat: 'NAME'},
  PARAM: {id: 'PARAM', types: ["param"], definitionFiles: ["param"], definitionFormat: '[NAME]', previewDeclaration: true},
  COMMAND: {id: 'COMMAND', definitionFiles: ["rs2"], definitionFormat: '[command,NAME]'},
  SYNTH: {id: 'SOUND_SYNTH', types: ["synth"], definitionFiles: ["synth"], definitionFormat: 'NAME'},
  WALKTRIGGER: {id: 'WALKTRIGGER', types: ["walktrigger"], definitionFiles: ["rs2"], definitionFormat: '[walktrigger,NAME]'},
  IDK: {id: 'IDK', types: ["idk", "idkit"], definitionFiles: ["idk"], definitionFormat: '[NAME]'},
};

module.exports = matchType;
